<?php

namespace Database\Seeders;

use App\Models\Ciudades\ciudad;
use Illuminate\Database\Seeder;

class CiudadesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ciudades = [
            ['departamento_id' => 1, 'nombre' => 'Leticia'],
            ['departamento_id' => 1, 'nombre' => 'Puerto Nariño'],
            ['departamento_id' => 2, 'nombre' => 'Abejorral'],
            ['departamento_id' => 2, 'nombre' => 'Abriaquí'],
            ['departamento_id' => 2, 'nombre' => 'Alejandría'],
            ['departamento_id' => 2, 'nombre' => 'Amagá'],
            ['departamento_id' => 2, 'nombre' => 'Amalfi'],
            ['departamento_id' => 2, 'nombre' => 'Andes'],
            ['departamento_id' => 2, 'nombre' => 'Angelópolis'],
            ['departamento_id' => 2, 'nombre' => 'Angostura'],
            ['departamento_id' => 2, 'nombre' => 'Anorí'],
            ['departamento_id' => 2, 'nombre' => 'Anzá'],
            ['departamento_id' => 2, 'nombre' => 'Apartadó'],
            ['departamento_id' => 2, 'nombre' => 'Arboletes'],
            ['departamento_id' => 2, 'nombre' => 'Argelia'],
            ['departamento_id' => 2, 'nombre' => 'Armenia'],
            ['departamento_id' => 2, 'nombre' => 'Barbosa'],
            ['departamento_id' => 2, 'nombre' => 'Bello'],
            ['departamento_id' => 2, 'nombre' => 'Belmira'],
            ['departamento_id' => 2, 'nombre' => 'Betania'],
            ['departamento_id' => 2, 'nombre' => 'Betulia'],
            ['departamento_id' => 2, 'nombre' => 'Briceño'],
            ['departamento_id' => 2, 'nombre' => 'Buriticá'],
            ['departamento_id' => 2, 'nombre' => 'Cáceres'],
            ['departamento_id' => 2, 'nombre' => 'Caicedo'],
            ['departamento_id' => 2, 'nombre' => 'Caldas'],
            ['departamento_id' => 2, 'nombre' => 'Campamento'],
            ['departamento_id' => 2, 'nombre' => 'Cañasgordas'],
            ['departamento_id' => 2, 'nombre' => 'Caracolí'],
            ['departamento_id' => 2, 'nombre' => 'Caramanta'],
            ['departamento_id' => 2, 'nombre' => 'Carepa'],
            ['departamento_id' => 2, 'nombre' => 'Carolina del Príncipe'],
            ['departamento_id' => 2, 'nombre' => 'Caucasia'],
            ['departamento_id' => 2, 'nombre' => 'Chigorodó'],
            ['departamento_id' => 2, 'nombre' => 'Cisneros'],
            ['departamento_id' => 2, 'nombre' => 'Ciudad Bolívar'],
            ['departamento_id' => 2, 'nombre' => 'Cocorná'],
            ['departamento_id' => 2, 'nombre' => 'Concepción'],
            ['departamento_id' => 2, 'nombre' => 'Concordia'],
            ['departamento_id' => 2, 'nombre' => 'Copacabana'],
            ['departamento_id' => 2, 'nombre' => 'Dabeiba'],
            ['departamento_id' => 2, 'nombre' => 'Donmatías'],
            ['departamento_id' => 2, 'nombre' => 'Ebéjico'],
            ['departamento_id' => 2, 'nombre' => 'El Bagre'],
            ['departamento_id' => 2, 'nombre' => 'El Carmen de Viboral'],
            ['departamento_id' => 2, 'nombre' => 'El Peñol'],
            ['departamento_id' => 2, 'nombre' => 'El Retiro'],
            ['departamento_id' => 2, 'nombre' => 'El Santuario'],
            ['departamento_id' => 2, 'nombre' => 'Entrerríos'],
            ['departamento_id' => 2, 'nombre' => 'Envigado'],
            ['departamento_id' => 2, 'nombre' => 'Fredonia'],
            ['departamento_id' => 2, 'nombre' => 'Frontino'],
            ['departamento_id' => 2, 'nombre' => 'Giraldo'],
            ['departamento_id' => 2, 'nombre' => 'Girardota'],
            ['departamento_id' => 2, 'nombre' => 'Gómez Plata'],
            ['departamento_id' => 2, 'nombre' => 'Granada'],
            ['departamento_id' => 2, 'nombre' => 'Guadalupe'],
            ['departamento_id' => 2, 'nombre' => 'Guarne'],
            ['departamento_id' => 2, 'nombre' => 'Guatapé'],
            ['departamento_id' => 2, 'nombre' => 'Heliconia'],
            ['departamento_id' => 2, 'nombre' => 'Hispania'],
            ['departamento_id' => 2, 'nombre' => 'Itagüí'],
            ['departamento_id' => 2, 'nombre' => 'Ituango'],
            ['departamento_id' => 2, 'nombre' => 'Jardín'],
            ['departamento_id' => 2, 'nombre' => 'Jericó'],
            ['departamento_id' => 2, 'nombre' => 'La Ceja'],
            ['departamento_id' => 2, 'nombre' => 'La Estrella'],
            ['departamento_id' => 2, 'nombre' => 'La Pintada'],
            ['departamento_id' => 2, 'nombre' => 'La Unión'],
            ['departamento_id' => 2, 'nombre' => 'Liborina'],
            ['departamento_id' => 2, 'nombre' => 'Maceo'],
            ['departamento_id' => 2, 'nombre' => 'Marinilla'],
            ['departamento_id' => 2, 'nombre' => 'Medellín'],
            ['departamento_id' => 2, 'nombre' => 'Montebello'],
            ['departamento_id' => 2, 'nombre' => 'Murindó'],
            ['departamento_id' => 2, 'nombre' => 'Mutatá'],
            ['departamento_id' => 2, 'nombre' => 'Nariño'],
            ['departamento_id' => 2, 'nombre' => 'Nechí'],
            ['departamento_id' => 2, 'nombre' => 'Necoclí'],
            ['departamento_id' => 2, 'nombre' => 'Olaya'],
            ['departamento_id' => 2, 'nombre' => 'Peque'],
            ['departamento_id' => 2, 'nombre' => 'Pueblorrico'],
            ['departamento_id' => 2, 'nombre' => 'Puerto Berrío'],
            ['departamento_id' => 2, 'nombre' => 'Puerto Nare'],
            ['departamento_id' => 2, 'nombre' => 'Puerto Triunfo'],
            ['departamento_id' => 2, 'nombre' => 'Remedios'],
            ['departamento_id' => 2, 'nombre' => 'Rionegro'],
            ['departamento_id' => 2, 'nombre' => 'Sabanalarga'],
            ['departamento_id' => 2, 'nombre' => 'Sabaneta'],
            ['departamento_id' => 2, 'nombre' => 'Salgar'],
            ['departamento_id' => 2, 'nombre' => 'San Andrés de Cuerquia'],
            ['departamento_id' => 2, 'nombre' => 'San Carlos'],
            ['departamento_id' => 2, 'nombre' => 'San Francisco'],
            ['departamento_id' => 2, 'nombre' => 'San Jerónimo'],
            ['departamento_id' => 2, 'nombre' => 'San José de la Montaña'],
            ['departamento_id' => 2, 'nombre' => 'San Juan de Urabá'],
            ['departamento_id' => 2, 'nombre' => 'San Luis'],
            ['departamento_id' => 2, 'nombre' => 'San Pedro de Urabá'],
            ['departamento_id' => 2, 'nombre' => 'San Pedro de los Milagros'],
            ['departamento_id' => 2, 'nombre' => 'San Rafael'],
            ['departamento_id' => 2, 'nombre' => 'San Roque'],
            ['departamento_id' => 2, 'nombre' => 'San Vicente'],
            ['departamento_id' => 2, 'nombre' => 'Santa Bárbara'],
            ['departamento_id' => 2, 'nombre' => 'Santa Fe de Antioquia'],
            ['departamento_id' => 2, 'nombre' => 'Santa Rosa de Osos'],
            ['departamento_id' => 2, 'nombre' => 'Santo Domingo'],
            ['departamento_id' => 2, 'nombre' => 'Segovia'],
            ['departamento_id' => 2, 'nombre' => 'Sonsón'],
            ['departamento_id' => 2, 'nombre' => 'Sopetrán'],
            ['departamento_id' => 2, 'nombre' => 'Támesis'],
            ['departamento_id' => 2, 'nombre' => 'Tarazá'],
            ['departamento_id' => 2, 'nombre' => 'Tarso'],
            ['departamento_id' => 2, 'nombre' => 'Titiribí'],
            ['departamento_id' => 2, 'nombre' => 'Toledo'],
            ['departamento_id' => 2, 'nombre' => 'Turbo'],
            ['departamento_id' => 2, 'nombre' => 'Uramita'],
            ['departamento_id' => 2, 'nombre' => 'Urrao'],
            ['departamento_id' => 2, 'nombre' => 'Valdivia'],
            ['departamento_id' => 2, 'nombre' => 'Valparaíso'],
            ['departamento_id' => 2, 'nombre' => 'Vegachí'],
            ['departamento_id' => 2, 'nombre' => 'Venecia'],
            ['departamento_id' => 2, 'nombre' => 'Vigía del Fuerte'],
            ['departamento_id' => 2, 'nombre' => 'Yalí'],
            ['departamento_id' => 2, 'nombre' => 'Yarumal'],
            ['departamento_id' => 2, 'nombre' => 'Yolombó'],
            ['departamento_id' => 2, 'nombre' => 'Yondó'],
            ['departamento_id' => 2, 'nombre' => 'Zaragoza'],
            ['departamento_id' => 3, 'nombre' => 'Arauca'],
            ['departamento_id' => 3, 'nombre' => 'Arauquita'],
            ['departamento_id' => 3, 'nombre' => 'Cravo Norte'],
            ['departamento_id' => 3, 'nombre' => 'Fortul'],
            ['departamento_id' => 3, 'nombre' => 'Puerto Rondón'],
            ['departamento_id' => 3, 'nombre' => 'Saravena'],
            ['departamento_id' => 3, 'nombre' => 'Tame'],
            ['departamento_id' => 4, 'nombre' => 'Baranoa'],
            ['departamento_id' => 4, 'nombre' => 'Barranquilla'],
            ['departamento_id' => 4, 'nombre' => 'Campo de la Cruz'],
            ['departamento_id' => 4, 'nombre' => 'Candelaria'],
            ['departamento_id' => 4, 'nombre' => 'Galapa'],
            ['departamento_id' => 4, 'nombre' => 'Juan de Acosta'],
            ['departamento_id' => 4, 'nombre' => 'Luruaco'],
            ['departamento_id' => 4, 'nombre' => 'Malambo'],
            ['departamento_id' => 4, 'nombre' => 'Manatí'],
            ['departamento_id' => 4, 'nombre' => 'Palmar de Varela'],
            ['departamento_id' => 4, 'nombre' => 'Piojó'],
            ['departamento_id' => 4, 'nombre' => 'Polonuevo'],
            ['departamento_id' => 4, 'nombre' => 'Ponedera'],
            ['departamento_id' => 4, 'nombre' => 'Puerto Colombia'],
            ['departamento_id' => 4, 'nombre' => 'Repelón'],
            ['departamento_id' => 4, 'nombre' => 'Sabanagrande'],
            ['departamento_id' => 4, 'nombre' => 'Sabanalarga'],
            ['departamento_id' => 4, 'nombre' => 'Santa Lucía'],
            ['departamento_id' => 4, 'nombre' => 'Santo Tomás'],
            ['departamento_id' => 4, 'nombre' => 'Soledad'],
            ['departamento_id' => 4, 'nombre' => 'Suán'],
            ['departamento_id' => 4, 'nombre' => 'Tubará'],
            ['departamento_id' => 4, 'nombre' => 'Usiacurí'],
            ['departamento_id' => 6, 'nombre' => 'Achí'],
            ['departamento_id' => 6, 'nombre' => 'Altos del Rosario'],
            ['departamento_id' => 6, 'nombre' => 'Arenal'],
            ['departamento_id' => 6, 'nombre' => 'Arjona'],
            ['departamento_id' => 6, 'nombre' => 'Arroyohondo'],
            ['departamento_id' => 6, 'nombre' => 'Barranco de Loba'],
            ['departamento_id' => 6, 'nombre' => 'Brazuelo de Papayal'],
            ['departamento_id' => 6, 'nombre' => 'Calamar'],
            ['departamento_id' => 6, 'nombre' => 'Cantagallo'],
            ['departamento_id' => 6, 'nombre' => 'Cartagena de Indias'],
            ['departamento_id' => 6, 'nombre' => 'Cicuco'],
            ['departamento_id' => 6, 'nombre' => 'Clemencia'],
            ['departamento_id' => 6, 'nombre' => 'Córdoba'],
            ['departamento_id' => 6, 'nombre' => 'El Carmen de Bolívar'],
            ['departamento_id' => 6, 'nombre' => 'El Guamo'],
            ['departamento_id' => 6, 'nombre' => 'El Peñón'],
            ['departamento_id' => 6, 'nombre' => 'Hatillo de Loba'],
            ['departamento_id' => 6, 'nombre' => 'Magangué'],
            ['departamento_id' => 6, 'nombre' => 'Mahates'],
            ['departamento_id' => 6, 'nombre' => 'Margarita'],
            ['departamento_id' => 6, 'nombre' => 'María la Baja'],
            ['departamento_id' => 6, 'nombre' => 'Mompós'],
            ['departamento_id' => 6, 'nombre' => 'Montecristo'],
            ['departamento_id' => 6, 'nombre' => 'Morales'],
            ['departamento_id' => 6, 'nombre' => 'Norosí'],
            ['departamento_id' => 6, 'nombre' => 'Pinillos'],
            ['departamento_id' => 6, 'nombre' => 'Regidor'],
            ['departamento_id' => 6, 'nombre' => 'Río Viejo'],
            ['departamento_id' => 6, 'nombre' => 'San Cristóbal'],
            ['departamento_id' => 6, 'nombre' => 'San Estanislao'],
            ['departamento_id' => 6, 'nombre' => 'San Fernando'],
            ['departamento_id' => 6, 'nombre' => 'San Jacinto del Cauca'],
            ['departamento_id' => 6, 'nombre' => 'San Jacinto'],
            ['departamento_id' => 6, 'nombre' => 'San Juan Nepomuceno'],
            ['departamento_id' => 6, 'nombre' => 'San Martín de Loba'],
            ['departamento_id' => 6, 'nombre' => 'San Pablo'],
            ['departamento_id' => 6, 'nombre' => 'Santa Catalina'],
            ['departamento_id' => 6, 'nombre' => 'Santa Rosa'],
            ['departamento_id' => 6, 'nombre' => 'Santa Rosa del Sur'],
            ['departamento_id' => 6, 'nombre' => 'Simití'],
            ['departamento_id' => 6, 'nombre' => 'Soplaviento'],
            ['departamento_id' => 6, 'nombre' => 'Talaigua Nuevo'],
            ['departamento_id' => 6, 'nombre' => 'Tiquisio'],
            ['departamento_id' => 6, 'nombre' => 'Turbaco'],
            ['departamento_id' => 6, 'nombre' => 'Turbaná'],
            ['departamento_id' => 6, 'nombre' => 'Villanueva'],
            ['departamento_id' => 6, 'nombre' => 'Zambrano'],
            ['departamento_id' => 7, 'nombre' => 'Almeida'],
            ['departamento_id' => 7, 'nombre' => 'Aquitania'],
            ['departamento_id' => 7, 'nombre' => 'Arcabuco'],
            ['departamento_id' => 7, 'nombre' => 'Belén'],
            ['departamento_id' => 7, 'nombre' => 'Berbeo'],
            ['departamento_id' => 7, 'nombre' => 'Betéitiva'],
            ['departamento_id' => 7, 'nombre' => 'Boavita'],
            ['departamento_id' => 7, 'nombre' => 'Boyacá'],
            ['departamento_id' => 7, 'nombre' => 'Briceño'],
            ['departamento_id' => 7, 'nombre' => 'Buenavista'],
            ['departamento_id' => 7, 'nombre' => 'Busbanzá'],
            ['departamento_id' => 7, 'nombre' => 'Caldas'],
            ['departamento_id' => 7, 'nombre' => 'Campohermoso'],
            ['departamento_id' => 7, 'nombre' => 'Cerinza'],
            ['departamento_id' => 7, 'nombre' => 'Chinavita'],
            ['departamento_id' => 7, 'nombre' => 'Chiquinquirá'],
            ['departamento_id' => 7, 'nombre' => 'Chíquiza'],
            ['departamento_id' => 7, 'nombre' => 'Chiscas'],
            ['departamento_id' => 7, 'nombre' => 'Chita'],
            ['departamento_id' => 7, 'nombre' => 'Chitaraque'],
            ['departamento_id' => 7, 'nombre' => 'Chivatá'],
            ['departamento_id' => 7, 'nombre' => 'Chivor'],
            ['departamento_id' => 7, 'nombre' => 'Ciénega'],
            ['departamento_id' => 7, 'nombre' => 'Cómbita'],
            ['departamento_id' => 7, 'nombre' => 'Coper'],
            ['departamento_id' => 7, 'nombre' => 'Corrales'],
            ['departamento_id' => 7, 'nombre' => 'Covarachía'],
            ['departamento_id' => 7, 'nombre' => 'Cubará'],
            ['departamento_id' => 7, 'nombre' => 'Cucaita'],
            ['departamento_id' => 7, 'nombre' => 'Cuítiva'],
            ['departamento_id' => 7, 'nombre' => 'Duitama'],
            ['departamento_id' => 7, 'nombre' => 'El Cocuy'],
            ['departamento_id' => 7, 'nombre' => 'El Espino'],
            ['departamento_id' => 7, 'nombre' => 'Firavitoba'],
            ['departamento_id' => 7, 'nombre' => 'Floresta'],
            ['departamento_id' => 7, 'nombre' => 'Gachantivá'],
            ['departamento_id' => 7, 'nombre' => 'Gámeza'],
            ['departamento_id' => 7, 'nombre' => 'Garagoa'],
            ['departamento_id' => 7, 'nombre' => 'Guacamayas'],
            ['departamento_id' => 7, 'nombre' => 'Guateque'],
            ['departamento_id' => 7, 'nombre' => 'Guayatá'],
            ['departamento_id' => 7, 'nombre' => 'Güicán'],
            ['departamento_id' => 7, 'nombre' => 'Iza'],
            ['departamento_id' => 7, 'nombre' => 'Jenesano'],
            ['departamento_id' => 7, 'nombre' => 'Jericó'],
            ['departamento_id' => 7, 'nombre' => 'La Capilla'],
            ['departamento_id' => 7, 'nombre' => 'La Uvita'],
            ['departamento_id' => 7, 'nombre' => 'La Victoria'],
            ['departamento_id' => 7, 'nombre' => 'Labranzagrande'],
            ['departamento_id' => 7, 'nombre' => 'Macanal'],
            ['departamento_id' => 7, 'nombre' => 'Maripí'],
            ['departamento_id' => 7, 'nombre' => 'Miraflores'],
            ['departamento_id' => 7, 'nombre' => 'Mongua'],
            ['departamento_id' => 7, 'nombre' => 'Monguí'],
            ['departamento_id' => 7, 'nombre' => 'Moniquirá'],
            ['departamento_id' => 7, 'nombre' => 'Motavita'],
            ['departamento_id' => 7, 'nombre' => 'Muzo'],
            ['departamento_id' => 7, 'nombre' => 'Nobsa'],
            ['departamento_id' => 7, 'nombre' => 'Nuevo Colón'],
            ['departamento_id' => 7, 'nombre' => 'Oicatá'],
            ['departamento_id' => 7, 'nombre' => 'Otanche'],
            ['departamento_id' => 7, 'nombre' => 'Pachavita'],
            ['departamento_id' => 7, 'nombre' => 'Páez'],
            ['departamento_id' => 7, 'nombre' => 'Paipa'],
            ['departamento_id' => 7, 'nombre' => 'Pajarito'],
            ['departamento_id' => 7, 'nombre' => 'Panqueba'],
            ['departamento_id' => 7, 'nombre' => 'Pauna'],
            ['departamento_id' => 7, 'nombre' => 'Paya'],
            ['departamento_id' => 7, 'nombre' => 'Paz del Río'],
            ['departamento_id' => 7, 'nombre' => 'Pesca'],
            ['departamento_id' => 7, 'nombre' => 'Pisba'],
            ['departamento_id' => 7, 'nombre' => 'Puerto Boyacá'],
            ['departamento_id' => 7, 'nombre' => 'Quípama'],
            ['departamento_id' => 7, 'nombre' => 'Ramiriquí'],
            ['departamento_id' => 7, 'nombre' => 'Ráquira'],
            ['departamento_id' => 7, 'nombre' => 'Rondón'],
            ['departamento_id' => 7, 'nombre' => 'Saboyá'],
            ['departamento_id' => 7, 'nombre' => 'Sáchica'],
            ['departamento_id' => 7, 'nombre' => 'Samacá'],
            ['departamento_id' => 7, 'nombre' => 'San Eduardo'],
            ['departamento_id' => 7, 'nombre' => 'San José de Pare'],
            ['departamento_id' => 7, 'nombre' => 'San Luis de Gaceno'],
            ['departamento_id' => 7, 'nombre' => 'San Mateo'],
            ['departamento_id' => 7, 'nombre' => 'San Miguel de Sema'],
            ['departamento_id' => 7, 'nombre' => 'San Pablo de Borbur'],
            ['departamento_id' => 7, 'nombre' => 'Santa María'],
            ['departamento_id' => 7, 'nombre' => 'Santa Rosa de Viterbo'],
            ['departamento_id' => 7, 'nombre' => 'Santa Sofía'],
            ['departamento_id' => 7, 'nombre' => 'Santana'],
            ['departamento_id' => 7, 'nombre' => 'Sativanorte'],
            ['departamento_id' => 7, 'nombre' => 'Sativasur'],
            ['departamento_id' => 7, 'nombre' => 'Siachoque'],
            ['departamento_id' => 7, 'nombre' => 'Soatá'],
            ['departamento_id' => 7, 'nombre' => 'Socha'],
            ['departamento_id' => 7, 'nombre' => 'Socotá'],
            ['departamento_id' => 7, 'nombre' => 'Sogamoso'],
            ['departamento_id' => 7, 'nombre' => 'Somondoco'],
            ['departamento_id' => 7, 'nombre' => 'Sora'],
            ['departamento_id' => 7, 'nombre' => 'Soracá'],
            ['departamento_id' => 7, 'nombre' => 'Sotaquirá'],
            ['departamento_id' => 7, 'nombre' => 'Susacón'],
            ['departamento_id' => 7, 'nombre' => 'Sutamarchán'],
            ['departamento_id' => 7, 'nombre' => 'Sutatenza'],
            ['departamento_id' => 7, 'nombre' => 'Tasco'],
            ['departamento_id' => 7, 'nombre' => 'Tenza'],
            ['departamento_id' => 7, 'nombre' => 'Tibaná'],
            ['departamento_id' => 7, 'nombre' => 'Tibasosa'],
            ['departamento_id' => 7, 'nombre' => 'Tinjacá'],
            ['departamento_id' => 7, 'nombre' => 'Tipacoque'],
            ['departamento_id' => 7, 'nombre' => 'Toca'],
            ['departamento_id' => 7, 'nombre' => 'Togüí'],
            ['departamento_id' => 7, 'nombre' => 'Tópaga'],
            ['departamento_id' => 7, 'nombre' => 'Tota'],
            ['departamento_id' => 7, 'nombre' => 'Tunja'],
            ['departamento_id' => 7, 'nombre' => 'Tununguá'],
            ['departamento_id' => 7, 'nombre' => 'Turmequé'],
            ['departamento_id' => 7, 'nombre' => 'Tuta'],
            ['departamento_id' => 7, 'nombre' => 'Tutazá'],
            ['departamento_id' => 7, 'nombre' => 'Úmbita'],
            ['departamento_id' => 7, 'nombre' => 'Ventaquemada'],
            ['departamento_id' => 7, 'nombre' => 'Villa de Leyva'],
            ['departamento_id' => 7, 'nombre' => 'Viracachá'],
            ['departamento_id' => 7, 'nombre' => 'Zetaquira'],
            ['departamento_id' => 8, 'nombre' => 'Aguadas'],
            ['departamento_id' => 8, 'nombre' => 'Anserma'],
            ['departamento_id' => 8, 'nombre' => 'Aranzazu'],
            ['departamento_id' => 8, 'nombre' => 'Belalcázar'],
            ['departamento_id' => 8, 'nombre' => 'Chinchiná'],
            ['departamento_id' => 8, 'nombre' => 'Filadelfia'],
            ['departamento_id' => 8, 'nombre' => 'La Dorada'],
            ['departamento_id' => 8, 'nombre' => 'La Merced'],
            ['departamento_id' => 8, 'nombre' => 'Manizales'],
            ['departamento_id' => 8, 'nombre' => 'Manzanares'],
            ['departamento_id' => 8, 'nombre' => 'Marmato'],
            ['departamento_id' => 8, 'nombre' => 'Marquetalia'],
            ['departamento_id' => 8, 'nombre' => 'Marulanda'],
            ['departamento_id' => 8, 'nombre' => 'Neira'],
            ['departamento_id' => 8, 'nombre' => 'Norcasia'],
            ['departamento_id' => 8, 'nombre' => 'Pácora'],
            ['departamento_id' => 8, 'nombre' => 'Palestina'],
            ['departamento_id' => 8, 'nombre' => 'Pensilvania'],
            ['departamento_id' => 8, 'nombre' => 'Riosucio'],
            ['departamento_id' => 8, 'nombre' => 'Risaralda'],
            ['departamento_id' => 8, 'nombre' => 'Salamina'],
            ['departamento_id' => 8, 'nombre' => 'Samaná'],
            ['departamento_id' => 8, 'nombre' => 'San José'],
            ['departamento_id' => 8, 'nombre' => 'Supía'],
            ['departamento_id' => 8, 'nombre' => 'Victoria'],
            ['departamento_id' => 8, 'nombre' => 'Villamaría'],
            ['departamento_id' => 8, 'nombre' => 'Viterbo'],
            ['departamento_id' => 9, 'nombre' => 'Albania'],
            ['departamento_id' => 9, 'nombre' => 'Belén de los Andaquíes'],
            ['departamento_id' => 9, 'nombre' => 'Cartagena del Chairá'],
            ['departamento_id' => 9, 'nombre' => 'Curillo'],
            ['departamento_id' => 9, 'nombre' => 'El Doncello'],
            ['departamento_id' => 9, 'nombre' => 'El Paujil'],
            ['departamento_id' => 9, 'nombre' => 'Florencia'],
            ['departamento_id' => 9, 'nombre' => 'La Montañita'],
            ['departamento_id' => 9, 'nombre' => 'Milán'],
            ['departamento_id' => 9, 'nombre' => 'Morelia'],
            ['departamento_id' => 9, 'nombre' => 'Puerto Rico'],
            ['departamento_id' => 9, 'nombre' => 'San José del Fragua'],
            ['departamento_id' => 9, 'nombre' => 'San Vicente del Caguán'],
            ['departamento_id' => 9, 'nombre' => 'Solano'],
            ['departamento_id' => 9, 'nombre' => 'Solita'],
            ['departamento_id' => 9, 'nombre' => 'Valparaíso'],
            ['departamento_id' => 10, 'nombre' => 'Aguazul'],
            ['departamento_id' => 10, 'nombre' => 'Chámeza'],
            ['departamento_id' => 10, 'nombre' => 'Hato Corozal'],
            ['departamento_id' => 10, 'nombre' => 'La Salina'],
            ['departamento_id' => 10, 'nombre' => 'Maní'],
            ['departamento_id' => 10, 'nombre' => 'Monterrey'],
            ['departamento_id' => 10, 'nombre' => 'Nunchía'],
            ['departamento_id' => 10, 'nombre' => 'Orocué'],
            ['departamento_id' => 10, 'nombre' => 'Paz de Ariporo'],
            ['departamento_id' => 10, 'nombre' => 'Pore'],
            ['departamento_id' => 10, 'nombre' => 'Recetor'],
            ['departamento_id' => 10, 'nombre' => 'Sabanalarga'],
            ['departamento_id' => 10, 'nombre' => 'Sácama'],
            ['departamento_id' => 10, 'nombre' => 'San Luis de Palenque'],
            ['departamento_id' => 10, 'nombre' => 'Támara'],
            ['departamento_id' => 10, 'nombre' => 'Tauramena'],
            ['departamento_id' => 10, 'nombre' => 'Trinidad'],
            ['departamento_id' => 10, 'nombre' => 'Villanueva'],
            ['departamento_id' => 10, 'nombre' => 'Yopal'],
            ['departamento_id' => 11, 'nombre' => 'Almaguer'],
            ['departamento_id' => 11, 'nombre' => 'Argelia'],
            ['departamento_id' => 11, 'nombre' => 'Balboa'],
            ['departamento_id' => 11, 'nombre' => 'Bolívar'],
            ['departamento_id' => 11, 'nombre' => 'Buenos Aires'],
            ['departamento_id' => 11, 'nombre' => 'Cajibío'],
            ['departamento_id' => 11, 'nombre' => 'Caldono'],
            ['departamento_id' => 11, 'nombre' => 'Caloto'],
            ['departamento_id' => 11, 'nombre' => 'Corinto'],
            ['departamento_id' => 11, 'nombre' => 'El Tambo'],
            ['departamento_id' => 11, 'nombre' => 'Florencia'],
            ['departamento_id' => 11, 'nombre' => 'Guachené'],
            ['departamento_id' => 11, 'nombre' => 'Guapí'],
            ['departamento_id' => 11, 'nombre' => 'Inzá'],
            ['departamento_id' => 11, 'nombre' => 'Jambaló'],
            ['departamento_id' => 11, 'nombre' => 'La Sierra'],
            ['departamento_id' => 11, 'nombre' => 'La Vega'],
            ['departamento_id' => 11, 'nombre' => 'López de Micay'],
            ['departamento_id' => 11, 'nombre' => 'Mercaderes'],
            ['departamento_id' => 11, 'nombre' => 'Miranda'],
            ['departamento_id' => 11, 'nombre' => 'Morales'],
            ['departamento_id' => 11, 'nombre' => 'Padilla'],
            ['departamento_id' => 11, 'nombre' => 'Páez'],
            ['departamento_id' => 11, 'nombre' => 'Patía'],
            ['departamento_id' => 11, 'nombre' => 'Piamonte'],
            ['departamento_id' => 11, 'nombre' => 'Piendamó'],
            ['departamento_id' => 11, 'nombre' => 'Popayán'],
            ['departamento_id' => 11, 'nombre' => 'Puerto Tejada'],
            ['departamento_id' => 11, 'nombre' => 'Puracé'],
            ['departamento_id' => 11, 'nombre' => 'Rosas'],
            ['departamento_id' => 11, 'nombre' => 'San Sebastián'],
            ['departamento_id' => 11, 'nombre' => 'Santa Rosa'],
            ['departamento_id' => 11, 'nombre' => 'Santander de Quilichao'],
            ['departamento_id' => 11, 'nombre' => 'Silvia'],
            ['departamento_id' => 11, 'nombre' => 'Sotará'],
            ['departamento_id' => 11, 'nombre' => 'Suárez'],
            ['departamento_id' => 11, 'nombre' => 'Sucre'],
            ['departamento_id' => 11, 'nombre' => 'Timbío'],
            ['departamento_id' => 11, 'nombre' => 'Timbiquí'],
            ['departamento_id' => 11, 'nombre' => 'Toribío'],
            ['departamento_id' => 11, 'nombre' => 'Totoró'],
            ['departamento_id' => 11, 'nombre' => 'Villa Rica'],
            ['departamento_id' => 12, 'nombre' => 'Aguachica'],
            ['departamento_id' => 12, 'nombre' => 'Agustín Codazzi'],
            ['departamento_id' => 12, 'nombre' => 'Astrea'],
            ['departamento_id' => 12, 'nombre' => 'Becerril'],
            ['departamento_id' => 12, 'nombre' => 'Bosconia'],
            ['departamento_id' => 12, 'nombre' => 'Chimichagua'],
            ['departamento_id' => 12, 'nombre' => 'Chiriguaná'],
            ['departamento_id' => 12, 'nombre' => 'Curumaní'],
            ['departamento_id' => 12, 'nombre' => 'El Copey'],
            ['departamento_id' => 12, 'nombre' => 'El Paso'],
            ['departamento_id' => 12, 'nombre' => 'Gamarra'],
            ['departamento_id' => 12, 'nombre' => 'González'],
            ['departamento_id' => 12, 'nombre' => 'La Gloria (Cesar)'],
            ['departamento_id' => 12, 'nombre' => 'La Jagua de Ibirico'],
            ['departamento_id' => 12, 'nombre' => 'La Paz'],
            ['departamento_id' => 12, 'nombre' => 'Manaure Balcón del Cesar'],
            ['departamento_id' => 12, 'nombre' => 'Pailitas'],
            ['departamento_id' => 12, 'nombre' => 'Pelaya'],
            ['departamento_id' => 12, 'nombre' => 'Pueblo Bello'],
            ['departamento_id' => 12, 'nombre' => 'Río de Oro'],
            ['departamento_id' => 12, 'nombre' => 'San Alberto'],
            ['departamento_id' => 12, 'nombre' => 'San Diego'],
            ['departamento_id' => 12, 'nombre' => 'San Martín'],
            ['departamento_id' => 12, 'nombre' => 'Tamalameque'],
            ['departamento_id' => 12, 'nombre' => 'Valledupar'],
            ['departamento_id' => 13, 'nombre' => 'Acandí'],
            ['departamento_id' => 13, 'nombre' => 'Alto Baudó'],
            ['departamento_id' => 13, 'nombre' => 'Bagadó'],
            ['departamento_id' => 13, 'nombre' => 'Bahía Solano'],
            ['departamento_id' => 13, 'nombre' => 'Bajo Baudó'],
            ['departamento_id' => 13, 'nombre' => 'Bojayá'],
            ['departamento_id' => 13, 'nombre' => 'Cantón de San Pablo'],
            ['departamento_id' => 13, 'nombre' => 'Cértegui'],
            ['departamento_id' => 13, 'nombre' => 'Condoto'],
            ['departamento_id' => 13, 'nombre' => 'El Atrato'],
            ['departamento_id' => 13, 'nombre' => 'El Carmen de Atrato'],
            ['departamento_id' => 13, 'nombre' => 'El Carmen del Darién'],
            ['departamento_id' => 13, 'nombre' => 'Istmina'],
            ['departamento_id' => 13, 'nombre' => 'Juradó'],
            ['departamento_id' => 13, 'nombre' => 'Litoral de San Juan'],
            ['departamento_id' => 13, 'nombre' => 'Lloró'],
            ['departamento_id' => 13, 'nombre' => 'Medio Atrato'],
            ['departamento_id' => 13, 'nombre' => 'Medio Baudó'],
            ['departamento_id' => 13, 'nombre' => 'Medio San Juan'],
            ['departamento_id' => 13, 'nombre' => 'Nóvita'],
            ['departamento_id' => 13, 'nombre' => 'Nuquí'],
            ['departamento_id' => 13, 'nombre' => 'Quibdó'],
            ['departamento_id' => 13, 'nombre' => 'Río Iró'],
            ['departamento_id' => 13, 'nombre' => 'Río Quito'],
            ['departamento_id' => 13, 'nombre' => 'Riosucio'],
            ['departamento_id' => 13, 'nombre' => 'San José del Palmar'],
            ['departamento_id' => 13, 'nombre' => 'Sipí'],
            ['departamento_id' => 13, 'nombre' => 'Tadó'],
            ['departamento_id' => 13, 'nombre' => 'Unión Panamericana'],
            ['departamento_id' => 13, 'nombre' => 'Unguía'],
            ['departamento_id' => 15, 'nombre' => 'Agua de Dios'],
            ['departamento_id' => 15, 'nombre' => 'Albán'],
            ['departamento_id' => 15, 'nombre' => 'Anapoima'],
            ['departamento_id' => 15, 'nombre' => 'Anolaima'],
            ['departamento_id' => 15, 'nombre' => 'Apulo'],
            ['departamento_id' => 15, 'nombre' => 'Arbeláez'],
            ['departamento_id' => 15, 'nombre' => 'Beltrán'],
            ['departamento_id' => 15, 'nombre' => 'Bituima'],
            ['departamento_id' => 5, 'nombre' => 'Bogotá'],
            ['departamento_id' => 15, 'nombre' => 'Bojacá'],
            ['departamento_id' => 15, 'nombre' => 'Cabrera'],
            ['departamento_id' => 15, 'nombre' => 'Cachipay'],
            ['departamento_id' => 15, 'nombre' => 'Cajicá'],
            ['departamento_id' => 15, 'nombre' => 'Caparrapí'],
            ['departamento_id' => 15, 'nombre' => 'Cáqueza'],
            ['departamento_id' => 15, 'nombre' => 'Carmen de Carupa'],
            ['departamento_id' => 15, 'nombre' => 'Chaguaní'],
            ['departamento_id' => 15, 'nombre' => 'Chía'],
            ['departamento_id' => 15, 'nombre' => 'Chipaque'],
            ['departamento_id' => 15, 'nombre' => 'Choachí'],
            ['departamento_id' => 15, 'nombre' => 'Chocontá'],
            ['departamento_id' => 15, 'nombre' => 'Cogua'],
            ['departamento_id' => 15, 'nombre' => 'Cota'],
            ['departamento_id' => 15, 'nombre' => 'Cucunubá'],
            ['departamento_id' => 15, 'nombre' => 'El Colegio'],
            ['departamento_id' => 15, 'nombre' => 'El Peñón'],
            ['departamento_id' => 15, 'nombre' => 'El Rosal'],
            ['departamento_id' => 15, 'nombre' => 'Facatativá'],
            ['departamento_id' => 15, 'nombre' => 'Fómeque'],
            ['departamento_id' => 15, 'nombre' => 'Fosca'],
            ['departamento_id' => 15, 'nombre' => 'Funza'],
            ['departamento_id' => 15, 'nombre' => 'Fúquene'],
            ['departamento_id' => 15, 'nombre' => 'Fusagasugá'],
            ['departamento_id' => 15, 'nombre' => 'Gachalá'],
            ['departamento_id' => 15, 'nombre' => 'Gachancipá'],
            ['departamento_id' => 15, 'nombre' => 'Gachetá'],
            ['departamento_id' => 15, 'nombre' => 'Gama'],
            ['departamento_id' => 15, 'nombre' => 'Girardot'],
            ['departamento_id' => 15, 'nombre' => 'Granada'],
            ['departamento_id' => 15, 'nombre' => 'Guachetá'],
            ['departamento_id' => 15, 'nombre' => 'Guaduas'],
            ['departamento_id' => 15, 'nombre' => 'Guasca'],
            ['departamento_id' => 15, 'nombre' => 'Guataquí'],
            ['departamento_id' => 15, 'nombre' => 'Guatavita'],
            ['departamento_id' => 15, 'nombre' => 'Guayabal de Síquima'],
            ['departamento_id' => 15, 'nombre' => 'Guayabetal'],
            ['departamento_id' => 15, 'nombre' => 'Gutiérrez'],
            ['departamento_id' => 15, 'nombre' => 'Jerusalén'],
            ['departamento_id' => 15, 'nombre' => 'Junín'],
            ['departamento_id' => 15, 'nombre' => 'La Calera'],
            ['departamento_id' => 15, 'nombre' => 'La Mesa'],
            ['departamento_id' => 15, 'nombre' => 'La Palma'],
            ['departamento_id' => 15, 'nombre' => 'La Peña'],
            ['departamento_id' => 15, 'nombre' => 'La Vega'],
            ['departamento_id' => 15, 'nombre' => 'Lenguazaque'],
            ['departamento_id' => 15, 'nombre' => 'Machetá'],
            ['departamento_id' => 15, 'nombre' => 'Madrid'],
            ['departamento_id' => 15, 'nombre' => 'Manta'],
            ['departamento_id' => 15, 'nombre' => 'Medina'],
            ['departamento_id' => 15, 'nombre' => 'Mosquera'],
            ['departamento_id' => 15, 'nombre' => 'Nariño'],
            ['departamento_id' => 15, 'nombre' => 'Nemocón'],
            ['departamento_id' => 15, 'nombre' => 'Nilo'],
            ['departamento_id' => 15, 'nombre' => 'Nimaima'],
            ['departamento_id' => 15, 'nombre' => 'Nocaima'],
            ['departamento_id' => 15, 'nombre' => 'Pacho'],
            ['departamento_id' => 15, 'nombre' => 'Paime'],
            ['departamento_id' => 15, 'nombre' => 'Pandi'],
            ['departamento_id' => 15, 'nombre' => 'Paratebueno'],
            ['departamento_id' => 15, 'nombre' => 'Pasca'],
            ['departamento_id' => 15, 'nombre' => 'Puerto Salgar'],
            ['departamento_id' => 15, 'nombre' => 'Pulí'],
            ['departamento_id' => 15, 'nombre' => 'Quebradanegra'],
            ['departamento_id' => 15, 'nombre' => 'Quetame'],
            ['departamento_id' => 15, 'nombre' => 'Quipile'],
            ['departamento_id' => 15, 'nombre' => 'Ricaurte'],
            ['departamento_id' => 15, 'nombre' => 'San Antonio del Tequendama'],
            ['departamento_id' => 15, 'nombre' => 'San Bernardo'],
            ['departamento_id' => 15, 'nombre' => 'San Cayetano'],
            ['departamento_id' => 15, 'nombre' => 'San Francisco'],
            ['departamento_id' => 15, 'nombre' => 'San Juan de Rioseco'],
            ['departamento_id' => 15, 'nombre' => 'Sasaima'],
            ['departamento_id' => 15, 'nombre' => 'Sesquilé'],
            ['departamento_id' => 15, 'nombre' => 'Sibaté'],
            ['departamento_id' => 15, 'nombre' => 'Silvania'],
            ['departamento_id' => 15, 'nombre' => 'Simijaca'],
            ['departamento_id' => 15, 'nombre' => 'Soacha'],
            ['departamento_id' => 15, 'nombre' => 'Sopó'],
            ['departamento_id' => 15, 'nombre' => 'Subachoque'],
            ['departamento_id' => 15, 'nombre' => 'Suesca'],
            ['departamento_id' => 15, 'nombre' => 'Supatá'],
            ['departamento_id' => 15, 'nombre' => 'Susa'],
            ['departamento_id' => 15, 'nombre' => 'Sutatausa'],
            ['departamento_id' => 15, 'nombre' => 'Tabio'],
            ['departamento_id' => 15, 'nombre' => 'Tausa'],
            ['departamento_id' => 15, 'nombre' => 'Tena'],
            ['departamento_id' => 15, 'nombre' => 'Tenjo'],
            ['departamento_id' => 15, 'nombre' => 'Tibacuy'],
            ['departamento_id' => 15, 'nombre' => 'Tibirita'],
            ['departamento_id' => 15, 'nombre' => 'Tocaima'],
            ['departamento_id' => 15, 'nombre' => 'Tocancipá'],
            ['departamento_id' => 15, 'nombre' => 'Topaipí'],
            ['departamento_id' => 15, 'nombre' => 'Ubalá'],
            ['departamento_id' => 15, 'nombre' => 'Ubaque'],
            ['departamento_id' => 15, 'nombre' => 'Ubaté'],
            ['departamento_id' => 15, 'nombre' => 'Une'],
            ['departamento_id' => 15, 'nombre' => 'Útica'],
            ['departamento_id' => 15, 'nombre' => 'Venecia'],
            ['departamento_id' => 15, 'nombre' => 'Vergara'],
            ['departamento_id' => 15, 'nombre' => 'Vianí'],
            ['departamento_id' => 15, 'nombre' => 'Villagómez'],
            ['departamento_id' => 15, 'nombre' => 'Villapinzón'],
            ['departamento_id' => 15, 'nombre' => 'Villeta'],
            ['departamento_id' => 15, 'nombre' => 'Viotá'],
            ['departamento_id' => 15, 'nombre' => 'Yacopí'],
            ['departamento_id' => 15, 'nombre' => 'Zipacón'],
            ['departamento_id' => 15, 'nombre' => 'Zipaquirá'],
            ['departamento_id' => 14, 'nombre' => 'Ayapel'],
            ['departamento_id' => 14, 'nombre' => 'Buenavista'],
            ['departamento_id' => 14, 'nombre' => 'Canalete'],
            ['departamento_id' => 14, 'nombre' => 'Cereté'],
            ['departamento_id' => 14, 'nombre' => 'Chimá'],
            ['departamento_id' => 14, 'nombre' => 'Chinú'],
            ['departamento_id' => 14, 'nombre' => 'Ciénaga de Oro'],
            ['departamento_id' => 14, 'nombre' => 'Cotorra'],
            ['departamento_id' => 14, 'nombre' => 'La Apartada'],
            ['departamento_id' => 14, 'nombre' => 'Lorica'],
            ['departamento_id' => 14, 'nombre' => 'Los Córdobas'],
            ['departamento_id' => 14, 'nombre' => 'Momil'],
            ['departamento_id' => 14, 'nombre' => 'Montelíbano'],
            ['departamento_id' => 14, 'nombre' => 'Montería'],
            ['departamento_id' => 14, 'nombre' => 'Moñitos'],
            ['departamento_id' => 14, 'nombre' => 'Planeta Rica'],
            ['departamento_id' => 14, 'nombre' => 'Pueblo Nuevo'],
            ['departamento_id' => 14, 'nombre' => 'Puerto Escondido'],
            ['departamento_id' => 14, 'nombre' => 'Puerto Libertador'],
            ['departamento_id' => 14, 'nombre' => 'Purísima'],
            ['departamento_id' => 14, 'nombre' => 'Sahagún'],
            ['departamento_id' => 14, 'nombre' => 'San Andrés de Sotavento'],
            ['departamento_id' => 14, 'nombre' => 'San Antero'],
            ['departamento_id' => 14, 'nombre' => 'San Bernardo del Viento'],
            ['departamento_id' => 14, 'nombre' => 'San Carlos'],
            ['departamento_id' => 14, 'nombre' => 'San José de Uré'],
            ['departamento_id' => 14, 'nombre' => 'San Pelayo'],
            ['departamento_id' => 14, 'nombre' => 'Tierralta'],
            ['departamento_id' => 14, 'nombre' => 'Tuchín'],
            ['departamento_id' => 14, 'nombre' => 'Valencia'],
            ['departamento_id' => 16, 'nombre' => 'Inírida'],
            ['departamento_id' => 17, 'nombre' => 'Calamar'],
            ['departamento_id' => 17, 'nombre' => 'El Retorno'],
            ['departamento_id' => 17, 'nombre' => 'Miraflores'],
            ['departamento_id' => 17, 'nombre' => 'San José del Guaviare'],
            ['departamento_id' => 18, 'nombre' => 'Acevedo'],
            ['departamento_id' => 18, 'nombre' => 'Agrado'],
            ['departamento_id' => 18, 'nombre' => 'Aipe'],
            ['departamento_id' => 18, 'nombre' => 'Algeciras'],
            ['departamento_id' => 18, 'nombre' => 'Altamira'],
            ['departamento_id' => 18, 'nombre' => 'Baraya'],
            ['departamento_id' => 18, 'nombre' => 'Campoalegre'],
            ['departamento_id' => 18, 'nombre' => 'Colombia'],
            ['departamento_id' => 18, 'nombre' => 'El Pital'],
            ['departamento_id' => 18, 'nombre' => 'Elías'],
            ['departamento_id' => 18, 'nombre' => 'Garzón'],
            ['departamento_id' => 18, 'nombre' => 'Gigante'],
            ['departamento_id' => 18, 'nombre' => 'Guadalupe'],
            ['departamento_id' => 18, 'nombre' => 'Hobo'],
            ['departamento_id' => 18, 'nombre' => 'Íquira'],
            ['departamento_id' => 18, 'nombre' => 'Isnos'],
            ['departamento_id' => 18, 'nombre' => 'La Argentina'],
            ['departamento_id' => 18, 'nombre' => 'La Plata'],
            ['departamento_id' => 18, 'nombre' => 'Nátaga'],
            ['departamento_id' => 18, 'nombre' => 'Neiva'],
            ['departamento_id' => 18, 'nombre' => 'Oporapa'],
            ['departamento_id' => 18, 'nombre' => 'Paicol'],
            ['departamento_id' => 18, 'nombre' => 'Palermo'],
            ['departamento_id' => 18, 'nombre' => 'Palestina'],
            ['departamento_id' => 18, 'nombre' => 'Pitalito'],
            ['departamento_id' => 18, 'nombre' => 'Rivera'],
            ['departamento_id' => 18, 'nombre' => 'Saladoblanco'],
            ['departamento_id' => 18, 'nombre' => 'San Agustín'],
            ['departamento_id' => 18, 'nombre' => 'Santa María'],
            ['departamento_id' => 18, 'nombre' => 'Suaza'],
            ['departamento_id' => 18, 'nombre' => 'Tarqui'],
            ['departamento_id' => 18, 'nombre' => 'Tello'],
            ['departamento_id' => 18, 'nombre' => 'Teruel'],
            ['departamento_id' => 18, 'nombre' => 'Tesalia'],
            ['departamento_id' => 18, 'nombre' => 'Timaná'],
            ['departamento_id' => 18, 'nombre' => 'Villavieja'],
            ['departamento_id' => 18, 'nombre' => 'Yaguará'],
            ['departamento_id' => 19, 'nombre' => 'Albania'],
            ['departamento_id' => 19, 'nombre' => 'Barrancas'],
            ['departamento_id' => 19, 'nombre' => 'Dibulla'],
            ['departamento_id' => 19, 'nombre' => 'Distracción'],
            ['departamento_id' => 19, 'nombre' => 'El Molino'],
            ['departamento_id' => 19, 'nombre' => 'Fonseca'],
            ['departamento_id' => 19, 'nombre' => 'Hatonuevo'],
            ['departamento_id' => 19, 'nombre' => 'La Jagua del Pilar'],
            ['departamento_id' => 19, 'nombre' => 'Maicao'],
            ['departamento_id' => 19, 'nombre' => 'Manaure'],
            ['departamento_id' => 19, 'nombre' => 'Riohacha'],
            ['departamento_id' => 19, 'nombre' => 'San Juan del Cesar'],
            ['departamento_id' => 19, 'nombre' => 'Uribia'],
            ['departamento_id' => 19, 'nombre' => 'Urumita'],
            ['departamento_id' => 19, 'nombre' => 'Villanueva'],
            ['departamento_id' => 20, 'nombre' => 'Algarrobo'],
            ['departamento_id' => 20, 'nombre' => 'Aracataca'],
            ['departamento_id' => 20, 'nombre' => 'Ariguaní'],
            ['departamento_id' => 20, 'nombre' => 'Cerro de San Antonio'],
            ['departamento_id' => 20, 'nombre' => 'Chibolo'],
            ['departamento_id' => 20, 'nombre' => 'Chibolo'],
            ['departamento_id' => 20, 'nombre' => 'Ciénaga'],
            ['departamento_id' => 20, 'nombre' => 'Concordia'],
            ['departamento_id' => 20, 'nombre' => 'El Banco'],
            ['departamento_id' => 20, 'nombre' => 'El Piñón'],
            ['departamento_id' => 20, 'nombre' => 'El Retén'],
            ['departamento_id' => 20, 'nombre' => 'Fundación'],
            ['departamento_id' => 20, 'nombre' => 'Guamal'],
            ['departamento_id' => 20, 'nombre' => 'Nueva Granada'],
            ['departamento_id' => 20, 'nombre' => 'Pedraza'],
            ['departamento_id' => 20, 'nombre' => 'Pijiño del Carmen'],
            ['departamento_id' => 20, 'nombre' => 'Pivijay'],
            ['departamento_id' => 20, 'nombre' => 'Plato'],
            ['departamento_id' => 20, 'nombre' => 'Pueblo Viejo'],
            ['departamento_id' => 20, 'nombre' => 'Remolino'],
            ['departamento_id' => 20, 'nombre' => 'Sabanas de San Ángel'],
            ['departamento_id' => 20, 'nombre' => 'Salamina'],
            ['departamento_id' => 20, 'nombre' => 'San Sebastián de Buenavista'],
            ['departamento_id' => 20, 'nombre' => 'San Zenón'],
            ['departamento_id' => 20, 'nombre' => 'Santa Ana'],
            ['departamento_id' => 20, 'nombre' => 'Santa Bárbara de Pinto'],
            ['departamento_id' => 20, 'nombre' => 'Santa Marta'],
            ['departamento_id' => 20, 'nombre' => 'Sitionuevo'],
            ['departamento_id' => 20, 'nombre' => 'Tenerife'],
            ['departamento_id' => 20, 'nombre' => 'Zapayán'],
            ['departamento_id' => 20, 'nombre' => 'Zona Bananera'],
            ['departamento_id' => 21, 'nombre' => 'Acacías'],
            ['departamento_id' => 21, 'nombre' => 'Barranca de Upía'],
            ['departamento_id' => 21, 'nombre' => 'Cabuyaro'],
            ['departamento_id' => 21, 'nombre' => 'Castilla la Nueva'],
            ['departamento_id' => 21, 'nombre' => 'Cubarral'],
            ['departamento_id' => 21, 'nombre' => 'Cumaral'],
            ['departamento_id' => 21, 'nombre' => 'El Calvario'],
            ['departamento_id' => 21, 'nombre' => 'El Castillo'],
            ['departamento_id' => 21, 'nombre' => 'El Dorado'],
            ['departamento_id' => 21, 'nombre' => 'Fuente de Oro'],
            ['departamento_id' => 21, 'nombre' => 'Granada'],
            ['departamento_id' => 21, 'nombre' => 'Guamal'],
            ['departamento_id' => 21, 'nombre' => 'La Macarena'],
            ['departamento_id' => 21, 'nombre' => 'La Uribe'],
            ['departamento_id' => 21, 'nombre' => 'Lejanías'],
            ['departamento_id' => 21, 'nombre' => 'Mapiripán'],
            ['departamento_id' => 21, 'nombre' => 'Mesetas'],
            ['departamento_id' => 21, 'nombre' => 'Puerto Concordia'],
            ['departamento_id' => 21, 'nombre' => 'Puerto Gaitán'],
            ['departamento_id' => 21, 'nombre' => 'Puerto Lleras'],
            ['departamento_id' => 21, 'nombre' => 'Puerto López'],
            ['departamento_id' => 21, 'nombre' => 'Puerto Rico'],
            ['departamento_id' => 21, 'nombre' => 'Restrepo'],
            ['departamento_id' => 21, 'nombre' => 'San Carlos de Guaroa'],
            ['departamento_id' => 21, 'nombre' => 'San Juan de Arama'],
            ['departamento_id' => 21, 'nombre' => 'San Juanito'],
            ['departamento_id' => 21, 'nombre' => 'San Martín'],
            ['departamento_id' => 21, 'nombre' => 'Villavicencio'],
            ['departamento_id' => 21, 'nombre' => 'Vista Hermosa'],
            ['departamento_id' => 22, 'nombre' => 'Aldana'],
            ['departamento_id' => 22, 'nombre' => 'Ancuyá'],
            ['departamento_id' => 22, 'nombre' => 'Arboleda'],
            ['departamento_id' => 22, 'nombre' => 'Barbacoas'],
            ['departamento_id' => 22, 'nombre' => 'Belén'],
            ['departamento_id' => 22, 'nombre' => 'Buesaco'],
            ['departamento_id' => 22, 'nombre' => 'Chachagüí'],
            ['departamento_id' => 22, 'nombre' => 'Colón'],
            ['departamento_id' => 22, 'nombre' => 'Consacá'],
            ['departamento_id' => 22, 'nombre' => 'Contadero'],
            ['departamento_id' => 22, 'nombre' => 'Córdoba'],
            ['departamento_id' => 22, 'nombre' => 'Cuaspud'],
            ['departamento_id' => 22, 'nombre' => 'Cumbal'],
            ['departamento_id' => 22, 'nombre' => 'Cumbitara'],
            ['departamento_id' => 22, 'nombre' => 'El Charco'],
            ['departamento_id' => 22, 'nombre' => 'El Peñol'],
            ['departamento_id' => 22, 'nombre' => 'El Rosario'],
            ['departamento_id' => 22, 'nombre' => 'El Tablón'],
            ['departamento_id' => 22, 'nombre' => 'El Tambo'],
            ['departamento_id' => 22, 'nombre' => 'Francisco Pizarro'],
            ['departamento_id' => 22, 'nombre' => 'Funes'],
            ['departamento_id' => 22, 'nombre' => 'Guachucal'],
            ['departamento_id' => 22, 'nombre' => 'Guaitarilla'],
            ['departamento_id' => 22, 'nombre' => 'Gualmatán'],
            ['departamento_id' => 22, 'nombre' => 'Iles'],
            ['departamento_id' => 22, 'nombre' => 'Imués'],
            ['departamento_id' => 22, 'nombre' => 'Ipiales'],
            ['departamento_id' => 22, 'nombre' => 'La Cruz'],
            ['departamento_id' => 22, 'nombre' => 'La Florida'],
            ['departamento_id' => 22, 'nombre' => 'La Llanada'],
            ['departamento_id' => 22, 'nombre' => 'La Tola'],
            ['departamento_id' => 22, 'nombre' => 'La Unión'],
            ['departamento_id' => 22, 'nombre' => 'Leiva'],
            ['departamento_id' => 22, 'nombre' => 'Linares'],
            ['departamento_id' => 22, 'nombre' => 'Los Andes'],
            ['departamento_id' => 22, 'nombre' => 'Magüí Payán'],
            ['departamento_id' => 22, 'nombre' => 'Mallama'],
            ['departamento_id' => 22, 'nombre' => 'Mosquera'],
            ['departamento_id' => 22, 'nombre' => 'Nariño'],
            ['departamento_id' => 22, 'nombre' => 'Olaya Herrera'],
            ['departamento_id' => 22, 'nombre' => 'Ospina'],
            ['departamento_id' => 22, 'nombre' => 'Pasto'],
            ['departamento_id' => 22, 'nombre' => 'Policarpa'],
            ['departamento_id' => 22, 'nombre' => 'Potosí'],
            ['departamento_id' => 22, 'nombre' => 'Providencia'],
            ['departamento_id' => 22, 'nombre' => 'Puerres'],
            ['departamento_id' => 22, 'nombre' => 'Pupiales'],
            ['departamento_id' => 22, 'nombre' => 'Ricaurte'],
            ['departamento_id' => 22, 'nombre' => 'Roberto Payán'],
            ['departamento_id' => 22, 'nombre' => 'Samaniego'],
            ['departamento_id' => 22, 'nombre' => 'San Bernardo'],
            ['departamento_id' => 22, 'nombre' => 'San José de Albán'],
            ['departamento_id' => 22, 'nombre' => 'San Lorenzo'],
            ['departamento_id' => 22, 'nombre' => 'San Pablo'],
            ['departamento_id' => 22, 'nombre' => 'San Pedro de Cartago'],
            ['departamento_id' => 22, 'nombre' => 'Sandoná'],
            ['departamento_id' => 22, 'nombre' => 'Santa Bárbara'],
            ['departamento_id' => 22, 'nombre' => 'Santacruz'],
            ['departamento_id' => 22, 'nombre' => 'Sapuyes'],
            ['departamento_id' => 22, 'nombre' => 'Taminango'],
            ['departamento_id' => 22, 'nombre' => 'Tangua'],
            ['departamento_id' => 22, 'nombre' => 'Tumaco'],
            ['departamento_id' => 22, 'nombre' => 'Túquerres'],
            ['departamento_id' => 22, 'nombre' => 'Yacuanquer'],
            ['departamento_id' => 23, 'nombre' => 'Ábrego'],
            ['departamento_id' => 23, 'nombre' => 'Arboledas'],
            ['departamento_id' => 23, 'nombre' => 'Bochalema'],
            ['departamento_id' => 23, 'nombre' => 'Bucarasica'],
            ['departamento_id' => 23, 'nombre' => 'Cáchira'],
            ['departamento_id' => 23, 'nombre' => 'Cácota'],
            ['departamento_id' => 23, 'nombre' => 'Chinácota'],
            ['departamento_id' => 23, 'nombre' => 'Chitagá'],
            ['departamento_id' => 23, 'nombre' => 'Convención'],
            ['departamento_id' => 23, 'nombre' => 'Cúcuta'],
            ['departamento_id' => 23, 'nombre' => 'Cucutilla'],
            ['departamento_id' => 23, 'nombre' => 'Duranía'],
            ['departamento_id' => 23, 'nombre' => 'El Carmen'],
            ['departamento_id' => 23, 'nombre' => 'El Tarra'],
            ['departamento_id' => 23, 'nombre' => 'El Zulia'],
            ['departamento_id' => 23, 'nombre' => 'Gramalote'],
            ['departamento_id' => 23, 'nombre' => 'Hacarí'],
            ['departamento_id' => 23, 'nombre' => 'Herrán'],
            ['departamento_id' => 23, 'nombre' => 'La Esperanza'],
            ['departamento_id' => 23, 'nombre' => 'La Playa de Belén'],
            ['departamento_id' => 23, 'nombre' => 'Labateca'],
            ['departamento_id' => 23, 'nombre' => 'Los Patios'],
            ['departamento_id' => 23, 'nombre' => 'Lourdes'],
            ['departamento_id' => 23, 'nombre' => 'Mutiscua'],
            ['departamento_id' => 23, 'nombre' => 'Ocaña'],
            ['departamento_id' => 23, 'nombre' => 'Pamplona'],
            ['departamento_id' => 23, 'nombre' => 'Pamplonita'],
            ['departamento_id' => 23, 'nombre' => 'Puerto Santander'],
            ['departamento_id' => 23, 'nombre' => 'Ragonvalia'],
            ['departamento_id' => 23, 'nombre' => 'Salazar de Las Palmas'],
            ['departamento_id' => 23, 'nombre' => 'San Calixto'],
            ['departamento_id' => 23, 'nombre' => 'San Cayetano'],
            ['departamento_id' => 23, 'nombre' => 'Santiago'],
            ['departamento_id' => 23, 'nombre' => 'Santo Domingo de Silos'],
            ['departamento_id' => 23, 'nombre' => 'Sardinata'],
            ['departamento_id' => 23, 'nombre' => 'Teorama'],
            ['departamento_id' => 23, 'nombre' => 'Tibú'],
            ['departamento_id' => 23, 'nombre' => 'Toledo'],
            ['departamento_id' => 23, 'nombre' => 'Villa Caro'],
            ['departamento_id' => 23, 'nombre' => 'Villa del Rosario'],
            ['departamento_id' => 24, 'nombre' => 'Colón'],
            ['departamento_id' => 24, 'nombre' => 'Mocoa'],
            ['departamento_id' => 24, 'nombre' => 'Orito'],
            ['departamento_id' => 24, 'nombre' => 'Puerto Asís'],
            ['departamento_id' => 24, 'nombre' => 'Puerto Caicedo'],
            ['departamento_id' => 24, 'nombre' => 'Puerto Guzmán'],
            ['departamento_id' => 24, 'nombre' => 'Puerto Leguízamo'],
            ['departamento_id' => 24, 'nombre' => 'San Francisco'],
            ['departamento_id' => 24, 'nombre' => 'San Miguel'],
            ['departamento_id' => 24, 'nombre' => 'Santiago'],
            ['departamento_id' => 24, 'nombre' => 'Sibundoy'],
            ['departamento_id' => 24, 'nombre' => 'Valle del Guamuez'],
            ['departamento_id' => 24, 'nombre' => 'Villagarzón'],
            ['departamento_id' => 25, 'nombre' => 'Armenia'],
            ['departamento_id' => 25, 'nombre' => 'Buenavista'],
            ['departamento_id' => 25, 'nombre' => 'Calarcá'],
            ['departamento_id' => 25, 'nombre' => 'Circasia'],
            ['departamento_id' => 25, 'nombre' => 'Córdoba'],
            ['departamento_id' => 25, 'nombre' => 'Filandia'],
            ['departamento_id' => 25, 'nombre' => 'Génova'],
            ['departamento_id' => 25, 'nombre' => 'La Tebaida'],
            ['departamento_id' => 25, 'nombre' => 'Montenegro'],
            ['departamento_id' => 25, 'nombre' => 'Pijao'],
            ['departamento_id' => 25, 'nombre' => 'Quimbaya'],
            ['departamento_id' => 25, 'nombre' => 'Salento'],
            ['departamento_id' => 26, 'nombre' => 'Apía'],
            ['departamento_id' => 26, 'nombre' => 'Balboa'],
            ['departamento_id' => 26, 'nombre' => 'Belén de Umbría'],
            ['departamento_id' => 26, 'nombre' => 'Dosquebradas'],
            ['departamento_id' => 26, 'nombre' => 'Guática'],
            ['departamento_id' => 26, 'nombre' => 'La Celia'],
            ['departamento_id' => 26, 'nombre' => 'La Virginia'],
            ['departamento_id' => 26, 'nombre' => 'Marsella'],
            ['departamento_id' => 26, 'nombre' => 'Mistrató'],
            ['departamento_id' => 26, 'nombre' => 'Pereira'],
            ['departamento_id' => 26, 'nombre' => 'Pueblo Rico'],
            ['departamento_id' => 26, 'nombre' => 'Quinchía'],
            ['departamento_id' => 26, 'nombre' => 'Santa Rosa de Cabal'],
            ['departamento_id' => 26, 'nombre' => 'Santuario'],
            ['departamento_id' => 27, 'nombre' => 'Providencia y Santa Catalina Islas'],
            ['departamento_id' => 27, 'nombre' => 'San Andrés'],
            ['departamento_id' => 28, 'nombre' => 'Aguada'],
            ['departamento_id' => 28, 'nombre' => 'Albania'],
            ['departamento_id' => 28, 'nombre' => 'Aratoca'],
            ['departamento_id' => 28, 'nombre' => 'Barbosa'],
            ['departamento_id' => 28, 'nombre' => 'Barichara'],
            ['departamento_id' => 28, 'nombre' => 'Barrancabermeja'],
            ['departamento_id' => 28, 'nombre' => 'Betulia'],
            ['departamento_id' => 28, 'nombre' => 'Bolívar'],
            ['departamento_id' => 28, 'nombre' => 'Bucaramanga'],
            ['departamento_id' => 28, 'nombre' => 'Cabrera'],
            ['departamento_id' => 28, 'nombre' => 'California'],
            ['departamento_id' => 28, 'nombre' => 'Capitanejo'],
            ['departamento_id' => 28, 'nombre' => 'Carcasí'],
            ['departamento_id' => 28, 'nombre' => 'Cepitá'],
            ['departamento_id' => 28, 'nombre' => 'Cerrito'],
            ['departamento_id' => 28, 'nombre' => 'Charalá'],
            ['departamento_id' => 28, 'nombre' => 'Charta'],
            ['departamento_id' => 28, 'nombre' => 'Chima'],
            ['departamento_id' => 28, 'nombre' => 'Chipatá'],
            ['departamento_id' => 28, 'nombre' => 'Cimitarra'],
            ['departamento_id' => 28, 'nombre' => 'Concepción'],
            ['departamento_id' => 28, 'nombre' => 'Confines'],
            ['departamento_id' => 28, 'nombre' => 'Contratación'],
            ['departamento_id' => 28, 'nombre' => 'Coromoro'],
            ['departamento_id' => 28, 'nombre' => 'Curití'],
            ['departamento_id' => 28, 'nombre' => 'El Carmen de Chucurí'],
            ['departamento_id' => 28, 'nombre' => 'El Guacamayo'],
            ['departamento_id' => 28, 'nombre' => 'El Peñón'],
            ['departamento_id' => 28, 'nombre' => 'El Playón'],
            ['departamento_id' => 28, 'nombre' => 'El Socorro'],
            ['departamento_id' => 28, 'nombre' => 'Encino'],
            ['departamento_id' => 28, 'nombre' => 'Enciso'],
            ['departamento_id' => 28, 'nombre' => 'Florián'],
            ['departamento_id' => 28, 'nombre' => 'Floridablanca'],
            ['departamento_id' => 28, 'nombre' => 'Galán'],
            ['departamento_id' => 28, 'nombre' => 'Gámbita'],
            ['departamento_id' => 28, 'nombre' => 'Girón'],
            ['departamento_id' => 28, 'nombre' => 'Guaca'],
            ['departamento_id' => 28, 'nombre' => 'Guadalupe'],
            ['departamento_id' => 28, 'nombre' => 'Guapotá'],
            ['departamento_id' => 28, 'nombre' => 'Guavatá'],
            ['departamento_id' => 28, 'nombre' => 'Güepsa'],
            ['departamento_id' => 28, 'nombre' => 'Hato'],
            ['departamento_id' => 28, 'nombre' => 'Jesús María'],
            ['departamento_id' => 28, 'nombre' => 'Jordán'],
            ['departamento_id' => 28, 'nombre' => 'La Belleza'],
            ['departamento_id' => 28, 'nombre' => 'La Paz'],
            ['departamento_id' => 28, 'nombre' => 'Landázuri'],
            ['departamento_id' => 28, 'nombre' => 'Lebrija'],
            ['departamento_id' => 28, 'nombre' => 'Los Santos'],
            ['departamento_id' => 28, 'nombre' => 'Macaravita'],
            ['departamento_id' => 28, 'nombre' => 'Málaga'],
            ['departamento_id' => 28, 'nombre' => 'Matanza'],
            ['departamento_id' => 28, 'nombre' => 'Mogotes'],
            ['departamento_id' => 28, 'nombre' => 'Molagavita'],
            ['departamento_id' => 28, 'nombre' => 'Ocamonte'],
            ['departamento_id' => 28, 'nombre' => 'Oiba'],
            ['departamento_id' => 28, 'nombre' => 'Onzaga'],
            ['departamento_id' => 28, 'nombre' => 'Palmar'],
            ['departamento_id' => 28, 'nombre' => 'Palmas del Socorro'],
            ['departamento_id' => 28, 'nombre' => 'Páramo'],
            ['departamento_id' => 28, 'nombre' => 'Piedecuesta'],
            ['departamento_id' => 28, 'nombre' => 'Pinchote'],
            ['departamento_id' => 28, 'nombre' => 'Puente Nacional'],
            ['departamento_id' => 28, 'nombre' => 'Puerto Parra'],
            ['departamento_id' => 28, 'nombre' => 'Puerto Wilches'],
            ['departamento_id' => 28, 'nombre' => 'Rionegro'],
            ['departamento_id' => 28, 'nombre' => 'Sabana de Torres'],
            ['departamento_id' => 28, 'nombre' => 'San Andrés'],
            ['departamento_id' => 28, 'nombre' => 'San Benito'],
            ['departamento_id' => 28, 'nombre' => 'San Gil'],
            ['departamento_id' => 28, 'nombre' => 'San Joaquín'],
            ['departamento_id' => 28, 'nombre' => 'San José de Miranda'],
            ['departamento_id' => 28, 'nombre' => 'San Miguel'],
            ['departamento_id' => 28, 'nombre' => 'San Vicente de Chucurí'],
            ['departamento_id' => 28, 'nombre' => 'Santa Bárbara'],
            ['departamento_id' => 28, 'nombre' => 'Santa Helena del Opón'],
            ['departamento_id' => 28, 'nombre' => 'Simacota'],
            ['departamento_id' => 28, 'nombre' => 'Suaita'],
            ['departamento_id' => 28, 'nombre' => 'Sucre'],
            ['departamento_id' => 28, 'nombre' => 'Suratá'],
            ['departamento_id' => 28, 'nombre' => 'Tona'],
            ['departamento_id' => 28, 'nombre' => 'Valle de San José'],
            ['departamento_id' => 28, 'nombre' => 'Vélez'],
            ['departamento_id' => 28, 'nombre' => 'Vetas'],
            ['departamento_id' => 28, 'nombre' => 'Villanueva'],
            ['departamento_id' => 28, 'nombre' => 'Zapatoca'],
            ['departamento_id' => 29, 'nombre' => 'Buenavista'],
            ['departamento_id' => 29, 'nombre' => 'Caimito'],
            ['departamento_id' => 29, 'nombre' => 'Chalán'],
            ['departamento_id' => 29, 'nombre' => 'Colosó'],
            ['departamento_id' => 29, 'nombre' => 'Corozal'],
            ['departamento_id' => 29, 'nombre' => 'Coveñas'],
            ['departamento_id' => 29, 'nombre' => 'El Roble'],
            ['departamento_id' => 29, 'nombre' => 'Galeras'],
            ['departamento_id' => 29, 'nombre' => 'Guaranda'],
            ['departamento_id' => 29, 'nombre' => 'La Unión'],
            ['departamento_id' => 29, 'nombre' => 'Los Palmitos'],
            ['departamento_id' => 29, 'nombre' => 'Majagual'],
            ['departamento_id' => 29, 'nombre' => 'Morroa'],
            ['departamento_id' => 29, 'nombre' => 'Ovejas'],
            ['departamento_id' => 29, 'nombre' => 'Sampués'],
            ['departamento_id' => 29, 'nombre' => 'San Antonio de Palmito'],
            ['departamento_id' => 29, 'nombre' => 'San Benito Abad'],
            ['departamento_id' => 29, 'nombre' => 'San Juan de Betulia'],
            ['departamento_id' => 29, 'nombre' => 'San Marcos'],
            ['departamento_id' => 29, 'nombre' => 'San Onofre'],
            ['departamento_id' => 29, 'nombre' => 'San Pedro'],
            ['departamento_id' => 29, 'nombre' => 'Sincé'],
            ['departamento_id' => 29, 'nombre' => 'Sincelejo'],
            ['departamento_id' => 29, 'nombre' => 'Sucre'],
            ['departamento_id' => 29, 'nombre' => 'Tolú'],
            ['departamento_id' => 29, 'nombre' => 'Tolú Viejo'],
            ['departamento_id' => 30, 'nombre' => 'Alpujarra'],
            ['departamento_id' => 30, 'nombre' => 'Alvarado'],
            ['departamento_id' => 30, 'nombre' => 'Ambalema'],
            ['departamento_id' => 30, 'nombre' => 'Anzoátegui'],
            ['departamento_id' => 30, 'nombre' => 'Armero'],
            ['departamento_id' => 30, 'nombre' => 'Ataco'],
            ['departamento_id' => 30, 'nombre' => 'Cajamarca'],
            ['departamento_id' => 30, 'nombre' => 'Carmen de Apicalá'],
            ['departamento_id' => 30, 'nombre' => 'Casabianca'],
            ['departamento_id' => 30, 'nombre' => 'Chaparral'],
            ['departamento_id' => 30, 'nombre' => 'Coello'],
            ['departamento_id' => 30, 'nombre' => 'Coyaima'],
            ['departamento_id' => 30, 'nombre' => 'Cunday'],
            ['departamento_id' => 30, 'nombre' => 'Dolores'],
            ['departamento_id' => 30, 'nombre' => 'El Espinal'],
            ['departamento_id' => 30, 'nombre' => 'Falán'],
            ['departamento_id' => 30, 'nombre' => 'Flandes'],
            ['departamento_id' => 30, 'nombre' => 'Fresno'],
            ['departamento_id' => 30, 'nombre' => 'Guamo'],
            ['departamento_id' => 30, 'nombre' => 'Herveo'],
            ['departamento_id' => 30, 'nombre' => 'Honda'],
            ['departamento_id' => 30, 'nombre' => 'Ibagué'],
            ['departamento_id' => 30, 'nombre' => 'Icononzo'],
            ['departamento_id' => 30, 'nombre' => 'Lérida'],
            ['departamento_id' => 30, 'nombre' => 'Líbano'],
            ['departamento_id' => 30, 'nombre' => 'Mariquita'],
            ['departamento_id' => 30, 'nombre' => 'Melgar'],
            ['departamento_id' => 30, 'nombre' => 'Murillo'],
            ['departamento_id' => 30, 'nombre' => 'Natagaima'],
            ['departamento_id' => 30, 'nombre' => 'Ortega'],
            ['departamento_id' => 30, 'nombre' => 'Palocabildo'],
            ['departamento_id' => 30, 'nombre' => 'Piedras'],
            ['departamento_id' => 30, 'nombre' => 'Planadas'],
            ['departamento_id' => 30, 'nombre' => 'Prado'],
            ['departamento_id' => 30, 'nombre' => 'Purificación'],
            ['departamento_id' => 30, 'nombre' => 'Rioblanco'],
            ['departamento_id' => 30, 'nombre' => 'Roncesvalles'],
            ['departamento_id' => 30, 'nombre' => 'Rovira'],
            ['departamento_id' => 30, 'nombre' => 'Saldaña'],
            ['departamento_id' => 30, 'nombre' => 'San Antonio'],
            ['departamento_id' => 30, 'nombre' => 'San Luis'],
            ['departamento_id' => 30, 'nombre' => 'Santa Isabel'],
            ['departamento_id' => 30, 'nombre' => 'Suárez'],
            ['departamento_id' => 30, 'nombre' => 'Valle de San Juan'],
            ['departamento_id' => 30, 'nombre' => 'Venadillo'],
            ['departamento_id' => 30, 'nombre' => 'Villahermosa'],
            ['departamento_id' => 30, 'nombre' => 'Villarrica'],
            ['departamento_id' => 31, 'nombre' => 'Alcalá'],
            ['departamento_id' => 31, 'nombre' => 'Andalucía'],
            ['departamento_id' => 31, 'nombre' => 'Ansermanuevo'],
            ['departamento_id' => 31, 'nombre' => 'Argelia'],
            ['departamento_id' => 31, 'nombre' => 'Bolívar'],
            ['departamento_id' => 31, 'nombre' => 'Buenaventura'],
            ['departamento_id' => 31, 'nombre' => 'Buga'],
            ['departamento_id' => 31, 'nombre' => 'Bugalagrande'],
            ['departamento_id' => 31, 'nombre' => 'Caicedonia'],
            ['departamento_id' => 31, 'nombre' => 'Cali'],
            ['departamento_id' => 31, 'nombre' => 'Calima'],
            ['departamento_id' => 31, 'nombre' => 'Candelaria'],
            ['departamento_id' => 31, 'nombre' => 'Cartago'],
            ['departamento_id' => 31, 'nombre' => 'Dagua'],
            ['departamento_id' => 31, 'nombre' => 'El Águila'],
            ['departamento_id' => 31, 'nombre' => 'El Cairo'],
            ['departamento_id' => 31, 'nombre' => 'El Cerrito'],
            ['departamento_id' => 31, 'nombre' => 'El Dovio'],
            ['departamento_id' => 31, 'nombre' => 'Florida'],
            ['departamento_id' => 31, 'nombre' => 'Ginebra'],
            ['departamento_id' => 31, 'nombre' => 'Guacarí'],
            ['departamento_id' => 31, 'nombre' => 'Jamundí'],
            ['departamento_id' => 31, 'nombre' => 'La Cumbre'],
            ['departamento_id' => 31, 'nombre' => 'La Unión'],
            ['departamento_id' => 31, 'nombre' => 'La Victoria'],
            ['departamento_id' => 31, 'nombre' => 'Obando'],
            ['departamento_id' => 31, 'nombre' => 'Palmira'],
            ['departamento_id' => 31, 'nombre' => 'Pradera'],
            ['departamento_id' => 31, 'nombre' => 'Restrepo'],
            ['departamento_id' => 31, 'nombre' => 'Riofrío'],
            ['departamento_id' => 31, 'nombre' => 'Roldanillo'],
            ['departamento_id' => 31, 'nombre' => 'San Pedro'],
            ['departamento_id' => 31, 'nombre' => 'Sevilla'],
            ['departamento_id' => 31, 'nombre' => 'Toro'],
            ['departamento_id' => 31, 'nombre' => 'Trujillo'],
            ['departamento_id' => 31, 'nombre' => 'Tuluá'],
            ['departamento_id' => 31, 'nombre' => 'Ulloa'],
            ['departamento_id' => 31, 'nombre' => 'Versalles'],
            ['departamento_id' => 31, 'nombre' => 'Vijes'],
            ['departamento_id' => 31, 'nombre' => 'Yotoco'],
            ['departamento_id' => 31, 'nombre' => 'Yumbo'],
            ['departamento_id' => 31, 'nombre' => 'Zarzal'],
            ['departamento_id' => 32, 'nombre' => 'Carurú'],
            ['departamento_id' => 32, 'nombre' => 'Mitú'],
            ['departamento_id' => 32, 'nombre' => 'Taraira'],
            ['departamento_id' => 33, 'nombre' => 'Cumaribo'],
            ['departamento_id' => 33, 'nombre' => 'La Primavera'],
            ['departamento_id' => 33, 'nombre' => 'Puerto Carreño'],
            ['departamento_id' => 33, 'nombre' => 'Santa Rosalía'],
        ];

        foreach ($ciudades as $ciudadData) {
            ciudad::updateOrCreate(
                [
                    'nombre' => $ciudadData['nombre'],
                    'departamento_id' => $ciudadData['departamento_id'],
                ],
                [
                    'codigo' => null,
                    'estado_id' => 1,
                    'creado_por' => 1,
                ]
            );
        }
    }
}
