const clienteMenu = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    subtitle: 'Resumen del negocio',
    icon: 'mdi-view-dashboard-outline',
    can: 'dashboard.view',
    children: [
      { id: 'dashboard-resumen', label: 'Resumen del negocio', can: 'dashboard.resumen' },
      { id: 'dashboard-ventas-dia', label: 'Ventas del dia', can: 'dashboard.ventas.dia' },
      { id: 'dashboard-ventas-semana', label: 'Ventas de la semana', can: 'dashboard.ventas.semana' },
      { id: 'dashboard-ventas-mes', label: 'Ventas del mes', can: 'dashboard.ventas.mes' },
      { id: 'dashboard-utilidad', label: 'Utilidad', can: 'dashboard.utilidad' },
      { id: 'dashboard-productos-top', label: 'Productos mas vendidos', can: 'dashboard.productos.top' },
      { id: 'dashboard-stock-bajo', label: 'Productos con poco stock', can: 'dashboard.stock.bajo' },
      { id: 'dashboard-ultimas-ventas', label: 'Ultimas ventas', can: 'dashboard.ventas.ultimas' },
      { id: 'dashboard-alertas', label: 'Alertas importantes', can: 'dashboard.alertas' },
    ],
  },
  {
    id: 'pos',
    label: 'Punto de Venta (POS)',
    subtitle: 'Caja y ventas rapidas',
    icon: 'mdi-cash-register',
    can: 'pos.view',
    children: [
      { id: 'pos-nueva-venta', label: 'Nueva venta', can: 'pos.nueva-venta' },
      { id: 'pos-cotizaciones', label: 'Cotizaciones', can: 'pos.cotizaciones' },
      { id: 'pos-devoluciones', label: 'Devoluciones', can: 'pos.devoluciones' },
      { id: 'pos-historial', label: 'Historial de ventas', can: 'pos.historial' },
      { id: 'pos-apartados', label: 'Apartados', can: 'pos.apartados' },
    ],
  },
  {
    id: 'inventario',
    label: 'Inventario',
    subtitle: 'Control de existencias',
    icon: 'mdi-package-variant-closed',
    can: 'inventario.view',
    children: [
      { id: 'inventario-productos', label: 'Productos', can: 'inventario.productos' },
      { id: 'inventario-categorias', label: 'Categorias', can: 'inventario.categorias' },
      { id: 'inventario-marcas', label: 'Marcas', can: 'inventario.marcas' },
      { id: 'inventario-unidades', label: 'Unidades de medida', can: 'inventario.unidades' },
      { id: 'inventario-entradas', label: 'Entradas', can: 'inventario.entradas' },
      { id: 'inventario-salidas', label: 'Salidas', can: 'inventario.salidas' },
      { id: 'inventario-ajustes', label: 'Ajustes de inventario', can: 'inventario.ajustes' },
      { id: 'inventario-kardex', label: 'Kardex', can: 'inventario.kardex' },
      { id: 'inventario-movimientos', label: 'Movimientos', can: 'inventario.movimientos' },
      { id: 'inventario-codigos-barras', label: 'Codigos de barras', can: 'inventario.codigos-barras' },
    ],
  },
  {
    id: 'compras',
    label: 'Compras',
    subtitle: 'Abastecimiento',
    icon: 'mdi-truck-delivery-outline',
    can: 'compras.view',
    children: [
      { id: 'compras-registrar', label: 'Registrar compra', can: 'compras.registrar' },
      { id: 'compras-ordenes', label: 'Ordenes de compra', can: 'compras.ordenes' },
      { id: 'compras-historial', label: 'Historial de compras', can: 'compras.historial' },
      { id: 'compras-recepciones', label: 'Recepciones', can: 'compras.recepciones' },
      { id: 'compras-gastos', label: 'Gastos de compra', can: 'compras.gastos' },
    ],
  },
  {
    id: 'clientes',
    label: 'Clientes',
    subtitle: 'Relacion comercial',
    icon: 'mdi-account-group-outline',
    can: 'clientes.view',
    children: [
      { id: 'clientes-lista', label: 'Clientes', can: 'clientes.lista' },
      { id: 'clientes-creditos', label: 'Creditos', can: 'clientes.creditos' },
      { id: 'clientes-estado-cuenta', label: 'Estado de cuenta', can: 'clientes.estado-cuenta' },
      { id: 'clientes-historial', label: 'Historial de compras', can: 'clientes.historial' },
      { id: 'clientes-fidelizacion', label: 'Programa de fidelizacion', can: 'clientes.fidelizacion.premium', tag: 'Premium' },
    ],
  },
  {
    id: 'proveedores',
    label: 'Proveedores',
    subtitle: 'Gestion de compras',
    icon: 'mdi-domain',
    can: 'proveedores.view',
    children: [
      { id: 'proveedores-lista', label: 'Lista de proveedores', can: 'proveedores.lista' },
      { id: 'proveedores-ordenes', label: 'Órdenes de compra', can: 'proveedores.ordenes' },
      { id: 'proveedores-compras', label: 'Compras', can: 'proveedores.compras' },
      { id: 'proveedores-devoluciones', label: 'Devoluciones', can: 'proveedores.devoluciones' },
      { id: 'proveedores-cotizaciones', label: 'Cotizaciones', can: 'proveedores.cotizaciones' },
      { id: 'proveedores-productos', label: 'Productos suministrados', can: 'proveedores.productos' },
      { id: 'proveedores-historial', label: 'Historial', can: 'proveedores.historial' },
      { id: 'proveedores-cxp', label: 'Cuentas por pagar', can: 'proveedores.cxp' },
    ],
  },
  {
    id: 'caja',
    label: 'Caja',
    subtitle: 'Operacion diaria',
    icon: 'mdi-safe-square-outline',
    can: 'caja.view',
    children: [
      { id: 'caja-cajas', label: 'Crear Cajas', can: 'caja.cajas' },
      { id: 'caja-control', label: 'Control de Caja', can: 'caja.control' },
      { id: 'caja-arqueo', label: 'Arqueo', can: 'caja.arqueo' },
      { id: 'caja-movimientos', label: 'Movimientos', can: 'caja.movimientos' },
      { id: 'caja-historial', label: 'Historial', can: 'caja.historial' },
    ],
  },
  {
    id: 'finanzas',
    label: 'Finanzas',
    subtitle: 'Control financiero',
    icon: 'mdi-cash-multiple',
    can: 'finanzas.view',
    children: [
      { id: 'finanzas-ingresos', label: 'Ingresos', can: 'finanzas.ingresos' },
      { id: 'finanzas-gastos', label: 'Gastos', can: 'finanzas.gastos' },
      { id: 'finanzas-cxc', label: 'Cuentas por cobrar', can: 'finanzas.cxc' },
      { id: 'finanzas-cxp', label: 'Cuentas por pagar', can: 'finanzas.cxp' },
      { id: 'finanzas-flujo-caja', label: 'Flujo de caja', can: 'finanzas.flujo-caja' },
    ],
  },
  {
    id: 'reportes',
    label: 'Reportes',
    subtitle: 'Analitica y exportacion',
    icon: 'mdi-chart-line',
    can: 'reportes.view',
    children: [
      { id: 'reportes-ventas', label: 'Ventas', can: 'reportes.ventas' },
      { id: 'reportes-compras', label: 'Compras', can: 'reportes.compras' },
      { id: 'reportes-inventario', label: 'Inventario', can: 'reportes.inventario' },
      { id: 'reportes-utilidad', label: 'Utilidad', can: 'reportes.utilidad' },
      { id: 'reportes-clientes', label: 'Clientes', can: 'reportes.clientes' },
      { id: 'reportes-productos', label: 'Productos', can: 'reportes.productos' },
      { id: 'reportes-caja', label: 'Caja', can: 'reportes.caja' },
      { id: 'reportes-impuestos', label: 'Impuestos', can: 'reportes.impuestos' },
      { id: 'reportes-exportar', label: 'Exportar PDF y Excel', can: 'reportes.exportar' },
    ],
  },
  {
    id: 'marketing',
    label: 'Marketing',
    subtitle: 'Promocion y retencion',
    icon: 'mdi-bullhorn-variant-outline',
    can: 'marketing.view.premium',
    tag: 'Premium',
    children: [
      { id: 'marketing-promociones', label: 'Promociones', can: 'marketing.promociones' },
      { id: 'marketing-cupones', label: 'Cupones', can: 'marketing.cupones' },
      { id: 'marketing-clientes-frecuentes', label: 'Clientes frecuentes', can: 'marketing.clientes-frecuentes' },
      { id: 'marketing-campanas-correo', label: 'Campanas por correo', can: 'marketing.campanas.correo' },
      { id: 'marketing-campanas-whatsapp', label: 'Campanas por WhatsApp', can: 'marketing.campanas.whatsapp' },
    ],
  },
  {
    id: 'empleados',
    label: 'Empleados',
    subtitle: 'Equipo y accesos',
    icon: 'mdi-account-tie-outline',
    can: 'empleados.view',
    children: [
      { id: 'empleados-usuarios', label: 'Usuarios', can: 'empleados.usuarios' },
      { id: 'empleados-roles', label: 'Roles', can: 'empleados.roles' },
      { id: 'empleados-permisos', label: 'Permisos', can: 'empleados.permisos' },
      { id: 'empleados-historial', label: 'Historial de actividades', can: 'empleados.historial' },
    ],
  },
  {
    id: 'empresa',
    label: 'Empresa',
    subtitle: 'Datos del negocio',
    icon: 'mdi-office-building-outline',
    can: 'empresa.view',
    children: [
      { id: 'empresa-informacion', label: 'Informacion', can: 'empresa.informacion' },
      { id: 'empresa-sucursales', label: 'Sucursales', can: 'empresa.sucursales' },
      { id: 'empresa-configuracion', label: 'Configuracion', can: 'empresa.configuracion' },
      { id: 'empresa-impuestos', label: 'Impuestos', can: 'empresa.impuestos' },
      { id: 'empresa-facturacion', label: 'Facturacion', can: 'empresa.facturacion' },
    ],
  },
  {
    id: 'notificaciones',
    label: 'Notificaciones',
    subtitle: 'Alertas operativas',
    icon: 'mdi-bell-outline',
    can: 'notificaciones.view',
    children: [
      { id: 'notificaciones-stock-bajo', label: 'Stock bajo', can: 'notificaciones.stock-bajo' },
      { id: 'notificaciones-agotados', label: 'Productos agotados', can: 'notificaciones.agotados' },
      { id: 'notificaciones-pagos', label: 'Pagos pendientes', can: 'notificaciones.pagos' },
      { id: 'notificaciones-actualizaciones', label: 'Actualizaciones', can: 'notificaciones.actualizaciones' },
    ],
  },
  {
    id: 'configuracion',
    label: 'Configuracion',
    subtitle: 'Parametros generales',
    icon: 'mdi-cog-outline',
    can: 'configuracion.view',
    children: [
      { id: 'configuracion-metodos-pago', label: 'Metodos de pago', can: 'configuracion.metodos-pago' },
      { id: 'configuracion-monedas', label: 'Monedas', can: 'configuracion.monedas' },
      { id: 'configuracion-impuestos', label: 'Impuestos', can: 'configuracion.impuestos' },
      { id: 'configuracion-numeracion', label: 'Numeracion de facturas', can: 'configuracion.numeracion' },
      { id: 'configuracion-impresoras', label: 'Impresoras', can: 'configuracion.impresoras' },
      { id: 'configuracion-backup', label: 'Copias de seguridad', can: 'configuracion.backup' },
      { id: 'configuracion-api', label: 'API', can: 'configuracion.api' },
      { id: 'configuracion-integraciones', label: 'Integraciones', can: 'configuracion.integraciones' },
    ],
  },
];

export default clienteMenu;
